title: Forza Panino's blog
description: >- # this means to ignore newlines until "baseurl:"
  A blog were you will find many write-ups that will help you to understand and solve challenges available in
  the most famous CTF platforms! 
baseurl: ""
url: ""
github_username:  forza-panino

# Build settings
remote_theme: pages-themes/slate@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-remote-theme

github:
  is_project_page: false
  repository_name: Forza Panino's blog
  owner_url: https://github.com/forza-panino/forza-panino.github.io
  owner_name: forza-panino

collections_dir: _collections
collections:
  CyberDefenders:
    output: true
    permalink: /:collection/:name